# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 480f301d63ff27fdc8d5af41f0f0b9947d179ae5ca98b8aa270113bffb08f6bf9e256f53c9767cc627b86062db7243d4a2a1c6c3a16e062acd5bfbb855ce77e1

test:
  secret_key_base: 334c973316364dfccf04b5853e88eb7395af0a89cc40204cc450c894f7efed383ccedd2cbfaf4d771030aa9a2e3cca4af2e04ffba2c1679b3aea289e7e9707ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
